package com.listmynest.model;

public enum AdminAction {
    LISTING_CREATED,
    LISTING_UPDATED,
    LISTING_STATUS_CHANGED,
    LISTING_REJECTED,
    LISTING_ACTIVATED,
    AGENT_CREATED,
    AGENT_UPDATED,
    AGENT_DEACTIVATED,
    SELLER_CREATED,
    SELLER_UPDATED,
    BUYER_VIEWED,
    IMPERSONATION_START,
    IMPERSONATION_END
}
